CREATE TABLE IF NOT EXISTS items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL CHECK(length(name) BETWEEN 1 AND 120),
    price NUMERIC NOT NULL DEFAULT 0 CHECK(price >= 0 AND price <= 999999.99),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
